### ISSUE TITLE
Fehlt bei PGS Basketid => Datenbestand die OID?

### ISSUE THREAD

**Issue by vvmruder** [openoereb/mgdm2oereb#20]
Normalerweise war das bei anderen Datensätzen immer so modelliert:
https://github.com/openoereb/mgdm2oereb/blob/master/data/ch.Planungszonen.sh.mgdm.v1_1.xtf#L153

Aber beim planerischen Gewässerschutz ist es nicht als OID verknüpft sondern als Textattribut:
`<BasketId>ch.SH.PlanerischerGewaesserschutz_V1_2.GWSZonen</BasketId>` => Zeile 739 https://github.com/openoereb/mgdm2oereb/blob/master/data/ch.Planerischergewaesserschutz.sh.mgdm.v1_2.xtf

Ist das so korrekt? Oder müssen hier die Daten überarbeitet werden?

**Comment by romefi** [comment]
Das ist bei den Datenmodellen unterschiedlich definiert. Bei Planungszonen als OID, beim planerischen Gewässerschutz als Text.

-> sollte in künftige MGDM-Überarbeitungen harmonisiert werden

**Comment by vvmruder** [comment]
@romefi Vielen Danke für die Aufklärung. Damit schliesse ich das Issue. :)
