### ISSUE TITLE
Lärmempfindlichkeitsstufen gibt fehlerhaftes Transfer-XTF

### ISSUE THREAD

**Issue by romefi** [openoereb/mgdm2oereb#33]
Wenn ich dieses XTF [sha_laermempfindlichkeitsstufen_v1_2.zip](https://github.com/openoereb/mgdm2oereb/files/11707228/sha_laermempfindlichkeitsstufen_v1_2.zip) transformiere, dann kommt ein fehlerhaftes Transfer-XTF raus. Siehe auch https://github.com/agiktsh/oereb-server.database/actions/runs/5222804373/jobs/9428784659.

Sind unsere Daten falsch oder liegt es an der Trafo?

**Comment by vvmruder** [comment]
Könnte es daran liegen, dass in eurem [Katalog](https://models.geo.sh.ch/AGI/OeREB/ch.sh.OeREBKRMlegdrst_V2_0.xml) zum Theme Lärmempfindlichkeitsstufen noch die Einträge neben `inKraft` fehlen. Z.B. `AenderungOhneVorwirkung`. Ich kann auf die Schnelle entsprechende Elemente nicht im Katalog finden.

Das würde erklären warum die Transformation dafür keine Verknüpfung finden kann. Beispielhaft mal Gemeinde 2937:
https://github.com/agiktsh/oereb-server.database/blob/master/ch.Laermempfindlichkeitsstufen-Laermempfindlichkeitsstufen_V1_2-ch.2937.Laermempfindlichkeitsstufen.xtf#L3711-L3715

In diesem Datensatz kommt `AenderungOhneVorwirkung` nämlich vor. Das trifft auch auf 2939 zu.

**Comment by romefi** [comment]
Richtig, Objekte in Änderungen gibt es in SH in den Lärmempfindlichkeitsstufen nicht. Deshalb auch keine Einträge im Katalog. War ein Fehler unsererseits bei der Aufbereitung vom MGDM.

Mit den nur rechtsgültigen Objekten läuft alles durch, so wie es sollte.
