### ISSUE TITLE
ilivalidator ohne --allObjectsAccessible

### ISSUE THREAD

**Issue by romefi** [openoereb/mgdm2oereb#37]
Prüft der ilivalidator mit der Option `--allObjectsAccessible`?

Im Moment wird bei der Datenprüfung ein Fehler ausgegeben, wenn externe Katalogeinträge nicht gefunden werden (was mit der Option `--allObjectsAccessible` verlangt werden kann). Für mgdm2oereb sind aber externe Katalogeinträge nicht relevant, d.h. die Option `--allObjectsAccessible` kann aus dem ilivalidator rausgenommen werden.

**Comment by edigonzales** [comment]
@romefi Meinst du beim Rahmenmodell-XTF? Die Offices und Gesetze sind ja dort nicht drin, oder? Darum allObjectsAccessible = true, jedoch dem Validator diese Files auch mitgeben beim Aufruf.

**Comment by edigonzales** [comment]
@romefi Prüft mit `--allObjectsAccessible`. Siehe https://github.com/openoereb/mgdm2oereb/blob/master/Makefile#L42

Wenn ihr es gleich macht wie wir, d.h. Offices und so nicht mitschicken, müsst ihr diese XTF beim ilivalidator-Aufruf mitangeben. Siehe analog: https://github.com/sogis/oereb-gretljobs/blob/main/oerebv2_gewaesserraum/build.gradle#L129

**Comment by romefi** [comment]
@edigonzales @vvmruder da war ich zu wenig präzis, entschuldigt. Es geht um die Prüfung der MGDM vor der Umwalndung duch mgdm2oereb und nicht um die ÖREB-Transferfiles. Gewisse MGDM (Nutzungsplanung, Waldreservate etc.) haben externe Kataloge, die fliegen im Moment beim Check auf die Nase.

**Comment by edigonzales** [comment]
@romefi Ah, ok. Dann bin ich auch deiner Meinung.

**Comment by romefi** [comment]
@vvmruder können wir das fixen? Im Moment läuft die Nutzungsplanung nicht durch mgdm2oereb.

**Comment by romefi** [comment]
@vvmruder Gleiches Problem haben wir auch bei den Waldreservaten

**Comment by vvmruder** [comment]
Ich schaue mir das an.

**Comment by vvmruder** [comment]
@edigonzales Kannst du hier schneller helfen? Das LOG sieht so aus: https://trafo.mgdm2oereb.sh.opengis.ch/mgdm2oereb_results/2023-07-04_1355061688478906.ch.Waldreservate.ch.SH.Waldreservate.OeREBKRMtrsfr_V2_0.93f7e6e4-dcd3-478b-8635-10e4e17da360.input.ili.log

Es ist das MGDM der Waldreservate. Ich lasse das vom https://github.com/sogis/ilivalidator-web-service-websocket validieren. Hast du einen schnellen Tip wie ich den konfiguriere damit er das richtige macht? Ich nehme an, standardmässig prüft er mit `allObjectsAccessible = true` oder?

Wie kann ich diesen Parameter am Server übergeben?

**Comment by vvmruder** [comment]
Habs gefunden dank der vorbildlichen API Dokumentation :)

**Comment by vvmruder** [comment]
@romefi Könntest du erneut testen? Ich habe jetzt einen Versuch gemacht und die Waldreservate liefen durch.

**Comment by vvmruder** [comment]
Zur Erklärung des Ablaufs: MGDM2OEREB Service prüft via ilivalidatorservice den Eingangsdatensatz (MGDM) und wenn der valide ist, gehts weiter. Nach der Trafo prüft MGDM2OEREB Service via ilivalidatorservice  den Resultatdatensatz. Wenn der valide ist dann gehts weiter. Falls eine Validierung nicht erfolgreich war, bricht der Prozess ab (entpsprechende Meldung via RSS Feed). Beide Validierungen waren mit `allObjectsAccessible=true` durchgeführt. Nun wird bei der Prüfung des MGDMS `allObjectsAccessible=false` und bei der Prüfung des Resultats (ÖREBtrsf) `allObjectsAccessible=true` verwendet.

**Comment by edigonzales** [comment]
> https://github.com/sogis/ilivalidator-web-service-websocket/blob/master/src/main/java/ch/so/agi/ilivalidator/IlivalidatorService.java#L61

Verwendest du nicht das hier: https://github.com/sogis/ilivalidator-web-service/blob/master/src/main/java/ch/so/agi/ilivalidator/controller/ApiController.java#L61

Mit dem Websocket-Teil denke ich nicht, dass es geht. Aber ja, scheint als hätte ich das in der API exponiert.

**Comment by romefi** [comment]
@vvmruder Danke für die Erklärung. Wenn die Daten so geprüft werden, dann passt das.

Hab die Nutzungsplanung nochmal getestet, aber funktioniert noch nicht https://trafo.mgdm2oereb.sh.opengis.ch/mgdm2oereb_results/2023-07-04_1528481688484528.ch.Nutzungsplanung.ch.2937.Nutzungsplanung.OeREBKRMtrsfr_V2_0.13d888d2-7ba0-4e78-9125-d82c7a2a0827.input.ili.log

**Comment by vvmruder** [comment]
> > https://github.com/sogis/ilivalidator-web-service-websocket/blob/master/src/main/java/ch/so/agi/ilivalidator/IlivalidatorService.java#L61
> 
> Verwendest du nicht das hier: https://github.com/sogis/ilivalidator-web-service/blob/master/src/main/java/ch/so/agi/ilivalidator/controller/ApiController.java#L61
> 
> Mit dem Websocket-Teil denke ich nicht, dass es geht. Aber ja, scheint als hätte ich das in der API exponiert.

@edigonzales Ja stimmt. War im Repo verrutscht.

**Comment by vvmruder** [comment]
> @vvmruder Danke für die Erklärung. Wenn die Daten so geprüft werden, dann passt das.
> 
> Hab die Nutzungsplanung nochmal getestet, aber funktioniert noch nicht https://trafo.mgdm2oereb.sh.opengis.ch/mgdm2oereb_results/2023-07-04_1528481688484528.ch.Nutzungsplanung.ch.2937.Nutzungsplanung.OeREBKRMtrsfr_V2_0.13d888d2-7ba0-4e78-9125-d82c7a2a0827.input.ili.log

Ich schaue weiter.

**Comment by edigonzales** [comment]
@vvmruder Es scheint, als hätte ich einen Test dafür: https://github.com/sogis/ilivalidator-web-service/blob/master/src/test/java/ch/so/agi/ilivalidator/ApiTests.java#L138

In der Hoffnung, dass ich genau das aber auch validieren!?

**Comment by vvmruder** [comment]
@romefi Hab noch einen Fehler entdeckt. Hab jetzt nochmal mit dem Nutzungsplanungsxtf getestet. Ging nun durch. Probierst du  nochmal zur Sicherheit?

**Comment by romefi** [comment]
@vvmruder Vielen Dank für den Fix. Jetzt laufen Nutzungsplanung und Waldreservate durch.
