### ISSUE TITLE
Planungszonen GR: Kantonales Gesetz wird bei Auszug nicht angegeben

### ISSUE THREAD

**Issue by weimir** [openoereb/mgdm2oereb#41]
Im Auszug wird bei manchen Planungszonen das kantonale Raumplanungsgesetz nicht angezeigt, obwohl es von mgdm2oereb heruntergeladen wurde und in den TRSF-Daten vorhanden ist. 
Das scheint immer dann der Fall zu sein, wenn mehr als eine Planungszone in einer Gemeinde ist. Es schaut so aus, als ob das Raumplanungsgesetz dann nur der einen, aber nicht der anderen Planungszone zugewiesen ist. Ich habe das auch im TRSF XTF verifiziert.

Im Anhang zwei Beispiele andhand der Gemeinden Thusis (3668, mgdm+trsf) und Albula/Alvra (3542, mgdm+trsf) sowie einer kurzen Zusammenstellung (.txt) der jeweiligen IDs.
[fehler_raumplanungsgesetz.zip](https://github.com/openoereb/mgdm2oereb/files/11868375/fehler_raumplanungsgesetz.zip)

**Comment by edigonzales** [comment]
Btw: Müsste ("Sollte") das Gesetz nicht sowieso nur jeweils dem Thema zugeordnet werden und nicht wie Rechtsvorschriften einzelnen Typen? War extra eine Änderung in ÖREB-V2.

**Comment by vvmruder** [comment]
@edigonzales Ja, danke für den Input. Das wäre tatsächlich die langfristig bessere Lösung. Die kantonalen Gesetze sollten im kvs Bereich abgelegt werden.

Hier handelt es sich aber um die spezielle Transformation aus ÖREBlex. Daher schaue ich mir das noch an.

**Comment by vvmruder** [comment]
@weimir Könntest du nochmals testen? Ich habe eine Anpassung vorgenommen. Und nach meinen Versuchen sollte es nun passen.

**Comment by weimir** [comment]
Perfekt, vielen Dank. Soweit ich das sehe, passt es jetzt.
@edigonzales Wir haben das bei uns (noch) nicht so umgesetzt, werden das aber in naher Zukunft prüfen..
