### ISSUE TITLE
Dokumente in Waldreservate werden nicht übernommen

### ISSUE THREAD

**Issue by romefi** [openoereb/mgdm2oereb#42]
@vvmruder Mit XTF 
[sh_waldreservate_v1_2.zip](https://github.com/openoereb/mgdm2oereb/files/11964530/sh_waldreservate_v1_2.zip) werden die Dokumente nicht in die Transferstruktur übernommen. Siehe https://trafo.mgdm2oereb.sh.opengis.ch/mgdm2oereb_results/326f3df1-3544-435e-8214-b95263349934/index.html

Ist das ein Fehler in den Daten oder in der Trafo?

**Comment by romefi** [comment]
Das MGDM sollte stimmen. Dort gibt es keinen Topic Transfermetadaten, wo die Basket-ID verknüpft werden muss.

**Comment by vvmruder** [comment]
Auch bei dieser Trafo kann ich keinen direkten Fehler sehen:
![image](https://github.com/openoereb/mgdm2oereb/assets/3714179/5df0b389-0021-430f-b552-2ae1e2e9d27b)

Dokumente sind dabei. Inhaltlich kann ich das aber nicht so gut beurteilen.

**Comment by vvmruder** [comment]
Die URL der Dokumente fehlt. Das muss gefixt werden!
