### ISSUE TITLE
Dokumente in statische Waldgrenzen werden nicht übernommen

### ISSUE THREAD

**Issue by romefi** [openoereb/mgdm2oereb#43]
@vvmruder Mit XTF [waldgrenzen_v1_2.zip](https://github.com/openoereb/mgdm2oereb/files/11967497/waldgrenzen_v1_2.zip) werden die Dokumente nicht in die Transferstruktur übernommen. Siehe https://trafo.mgdm2oereb.sh.opengis.ch/mgdm2oereb_results/44c58a3b-c515-4b18-ad59-9f91d920729d/index.html

Ist das ein Fehler in den Daten oder in der Trafo?

**Comment by vvmruder** [comment]
@romefi Ich habe das nochmal durchprobiert. Eigentlich kommen die Dokumente ja. Oder?

Z.B. hier: https://trafo.mgdm2oereb.sh.opengis.ch/mgdm2oereb_results/0b2e37fe-000e-4f12-98ad-b606eab4fb85/index.html

![image](https://github.com/openoereb/mgdm2oereb/assets/3714179/7d92b09b-bc72-49cb-ac62-100900c9f129)


Lokal getestet funktioniert es auch.

**Comment by vvmruder** [comment]
Die URL der Dokumente fehlt. Das muss gefixt werden!
