### ISSUE TITLE
Nutzungsplanung failed

### ISSUE THREAD

**Issue by romefi** [openoereb/mgdm2oereb#44]
Bei vier Gemeinden wird die Nutzungsplanung nicht transformiert, z.B. 
[bue_nutzungsplanung_v1_2.zip](https://github.com/openoereb/mgdm2oereb/files/12001400/bue_nutzungsplanung_v1_2.zip)

@vvmruder Hatten wir schon diskutiert, ob das Log-File über die Site verfügbar sein sollte (z.B. https://trafo.mgdm2oereb.sh.opengis.ch/oapi/jobs/b6d5610a-1f12-11ee-8d2d-0242ac103303). Würde uns das Debugging vereinfachen.

**Comment by vvmruder** [comment]
@romefi Ich konnte die angehängte XTF-Datei ohne Fehler transformieren. Eventuell war das ein temporäres Problem? Hier das Resultat: https://trafo.mgdm2oereb.sh.opengis.ch/oapi/jobs/a9ba15da-21bd-11ee-ae51-0242ac103305

**Comment by vvmruder** [comment]
Das Logging ist ja umgesetzt. Der Trafoservice kann damit auch inspiziert werden.

**Comment by vvmruder** [comment]
Nach Rückmeldung ok.
