### ISSUE TITLE
Bei KbS Transferstrukutr fehlt im Amt das Element AmtImWeb 

### ISSUE THREAD

**Issue by romefi** [openoereb/mgdm2oereb#47]
@vvmruder 
Bei der Trafo vom [KbS](https://github.com/openoereb/mgdm2oereb/blob/master/xsl/KbS_V1_5.trafo.xsl) fehlt das AmtImWeb in der Klasse Amt:
![image](https://github.com/openoereb/mgdm2oereb/assets/26796989/1a096ca5-b3d1-4d0d-be8e-4c1a2c84927b)

Die AmtImWeb sollte aus dem MGDM `Belastete_Standorte.ZustaendigkeitKataster.URL_Kataster` (ist ein Multilingual-Element) übernommen werden.

Nach ersten Tests könnte das auch den Fehler `An empty sequence is not allowed as the first argument of decodeURL()]` bei der PDF-Aufbereitung auslösen.

**Comment by vvmruder** [comment]
@romefi Ich schaue mir das an.

**Comment by vvmruder** [comment]
@romefi Ich habe den Fehler behoben und bereits neu ausgerollt. Ihr könnt testen.

**Comment by romefi** [comment]
@vvmruder Hab ein durcheinander gemacht. Statt URL_Kataster muss die URL_Behoerde rein.

Ich hab das mal selber versucht und ein Pull-Request gemacht: https://github.com/openoereb/mgdm2oereb/pull/50

Ausserdem habe ich noch beim Link in den Dokumenten einen Fehler entdeckt (auch wenn es der Filterfunktion widerspricht) und auch versucht zu korrigieren, Pull-Request wäre: https://github.com/openoereb/mgdm2oereb/pull/49

Könntest du diese zwei Pull-Requests anschauen und falls OK mergen?

Mit den vorhandenen AmtImWeb tritt der `decodeURL()`-Fehler nicht mehr auf. Die Ziellinie kommt immer näher.
