### ISSUE TITLE
Aufgestufte Lärmempfindlichkeitsstufen werden noch nicht berücksichtigt

### ISSUE THREAD

**Issue by romefi** [openoereb/mgdm2oereb#52]
Bei den Lärmempfindlichkeitsstufen gibt es aufgestufte Stufen. Diese sind im MGDM unter `Laermempfindlichkeitsstufen_V1_2.Geobasisdaten.Typ.Aufgestuft` gekennzeichnet. `true` wenn aufgestuft, `false` wenn nicht.

Im Katalog https://models.geo.sh.ch/AGI/OeREB/ch.sh.OeREBKRMlegdrst_V2_0.xml haben sie den Artcode (z.B. für aufgestufte ESIII) `ES_III_aufgestuft_inKraft`. Wahrscheinlich macht das die Umsetzung etwas schwierig.

Vorschlag:
mgdm2oereb füllt den ArtCode im Transferfile mit folgender Systematik ab: `Laermempfindlichkeitsstufen_V1_2.Geobasisdaten.Typ.Code`**_**`Laermempfindlichkeitsstufen_V1_2.Geobasisdaten.Typ.Aufgestuft`**_**`Laermempfindlichkeitsstufen_V1_2.Geobasisdaten.Laermempfindlichkeit_Zonenflaeche.Rechtsstatus`

Also z.B. für 
- eine aufgestufte ESII, die in Rechtskraft ist: `ESII_true_inKraft`
- eine nicht aufgestufte ESI, die in Aenderung ohne Vorwirkung ist: `ESI_false_AenderungOhneVorwirkung`

@vvmruder macht das Sinn? Wenn ja, würde ich unseren Katalog https://models.geo.sh.ch/AGI/OeREB/ch.sh.OeREBKRMlegdrst_V2_0.xml entsprechend umbauen. Von deiner Seite müsste das noch in der Trafo so umgesetzt werden.

**Comment by vvmruder** [comment]
@romefi In welchem Zeitraum müsste das umgesetzt werden? Grundsätzlich können wir das so machen. Sieht zumindest auf den ersten Blick ok aus. Könntest du mir hier einen aktualisierten Katalog hochladen? Dann kann ich das mit dem mal testen. An den Ausgangsdaten ändert sich ja nichts. Oder?

**Comment by romefi** [comment]
@vvmruder Ist eine Umsetzung bis Ende Woche realistisch? Oder bis wann könnte das aus deiner Sicht gemacht werden?

Klar, den aktualisierten Katalog findest du hier: [ch.sh.OeREBKRMlegdrst_V2_0.xml.zip](https://github.com/openoereb/mgdm2oereb/files/12160343/ch.sh.OeREBKRMlegdrst_V2_0.xml.zip)

Genau, an den Ausgangsdaten ändert sich nichts, die bleiben wie sie sind.

**Comment by vvmruder** [comment]
@romefi Ich schau mir das jetzt an.
