### ISSUE TITLE
Trafo bleibt hängen

### ISSUE THREAD

**Issue by romefi** [openoereb/mgdm2oereb#55]
@vvmruder hast du eine Idee, wieso das XTF [sha_nutzungsplanung_v1_2.zip](https://github.com/openoereb/mgdm2oereb/files/12258285/sha_nutzungsplanung_v1_2.zip) bei der [Trafo](https://trafo.mgdm2oereb.sh.opengis.ch/oapi/jobs/ed937e1c-3203-11ee-8b4f-0242ac103306) hängen bleibt? Bei diesem XTF haben wir die Bögen segmentiert, wodurch das XTF 22 MB gross wird. Könnte das allenfalls das Problem sein? Ich habe die Bögen mal bei einer kleineren Gemeinde segmentiert, da ist die Trafo durchgelaufen (auch wenn sie logischerweise etwas länger gebraucht hat).

**Comment by vvmruder** [comment]
@romefi Ich befürchte, es handelt sich dabei um ein Memory-Problem. Wenn ich das lokal ausführe und die Trafo beim Memory stark einschränke (128mb oder 256mb), wird der Trafoprozess gestoppt weil er das Memorylimit erreicht. Eventuell könnte das Problem sein. Ohne Limit läuft die Trafo sauber durch.

**Comment by romefi** [comment]
@vvmruder Das könnte gut sein... Braucht wahrscheinlich schon einiges mehr an Memory mit den segmentierten Objekten. Können wir mehr Memory freigeben oder brauchen wir eine grössere Kiste bei Exoscale?

**Comment by vvmruder** [comment]
@romefi Ich habe noch eine Einstellung angepasst. Wir hatten 8 Worker, die Trafos parallel ausführen können. Ich habe das mal auf 4 reduziert. Das sollte aus unseren bisherigen Erkenntnissen ja reichen und damit einigen Memory freigeben. Könntest du das nochmal mit besagtem XTF versuchen?

**Comment by romefi** [comment]
@vvmruder Danke für die Anpassung, damit funktioniert die Trafo. Dann lassen wir das so. 4 Worker sollten mehr als genug sein. Die Situation, dass wir mehr als ein XTF gleichzeitig transformieren müssen, ist eh sehr sehr klein.

**Comment by edigonzales** [comment]
Das ist das "Problem" von XSLT-Prozessoren. Grundsätzlich lässen alle die Chose mal ins Memory. Es gibt zwar solche, die Streamen können, aber je nach XPath-Ausdruck oder so geht das auch nicht immer.
