### ISSUE TITLE
Kantonale und Bundeskataloge am Beispiel der Nutzungsplanung

### ISSUE THREAD

**Issue by vvmruder** [openoereb/mgdm2oereb#8]
Es ist nicht ganz klar wie mit den externen Katalogen für das MGDM umzugehen ist. Einerseits existiert ein Katalog vom Bund:

http://models.geo.admin.ch/ARE/Nutzungsplanung_Catalogue_CH_V1_2_20210901.xml

Er definiert die durch den Bund vorgegebenen **Grundnutzungen** und **Überlagernde Nutzungsplaninhalte**.

Andererseits existiert der Katalog vom Kanton (Bereitstellung zusätzliche Infos Darstellungsdienst und Legendeneintrag):

https://models.geo.sh.ch/AGI/OeREB/ch.sh.OeREBKRMlegdrst_V2_0.xml

Beispielhaft sei aus dem MGDM Nutzungsplanung SH ein `Typ` herausgegriffen (repräsentiert die Stufe Gemeinde):

```xml
<Nutzungsplanung_V1_2.Geobasisdaten.Typ TID="d6378c94-291f-4bcf-ad75-5c266f6f40f2">
  <Code>sh.tha.112.0.39</Code>
  <Bezeichnung>Wohnzone 50</Bezeichnung>
  <Abkuerzung>W50</Abkuerzung>
  <Verbindlichkeit>Nutzungsplanfestlegung</Verbindlichkeit>
  <Nutzungsziffer>0.50</Nutzungsziffer>
  <Nutzungsziffer_Art>Ausnützungsziffer</Nutzungsziffer_Art>
  <Symbol>
    <BINBLBOX>aVZCT1J3MEtHZ29BQUFBTlNVaEVVZ0FBQUVjQUFBQWpDQVlBQUFERzFSZFRBQUFBZTBsRVFWUm9nZTNhc1JHRFFBd0FRYjJIVXR3Vjlia3Jlc0dSTTNNcEJMdVJRczJOUXEyWk9ZZS9YbmN2OEdUYmJ6aVB6NTE3UE1wNjd6UGpjcEk0UVp3Z1RoQW5pQlBFQ2VJRWNZSTRRWndnVGhBbmlCUEVDZUlFY1lJNFFad2dUaEFuaUJQRUNlSUVjWUk0UVp3Z1RoQW5pQlBXZUY2NjVITENGMTMzQlVWSEw3b3lBQUFBQUVsRlRrU3VRbUND</BINBLBOX>
    </Symbol>
  <Typ_Kt REF="fc822e2a-db6d-457d-bea0-5cf87129e6fc"></Typ_Kt>
</Nutzungsplanung_V1_2.Geobasisdaten.Typ>
```

Korrespondierend dazu aus dem MGDM Nutzungsplanung SH der `Typ_Kt` (repräsentiert die Stufe Kanton):

```xml
<Nutzungsplanung_V1_2.Geobasisdaten.Typ_Kt TID="fc822e2a-db6d-457d-bea0-5cf87129e6fc">
  <Code>112.0</Code>
  <Bezeichnung>Wohnzone 2</Bezeichnung>
  <Abkuerzung>W2</Abkuerzung>
  <Bemerkungen>Grundnutzungszone des Baugebietes (Bauzone)</Bemerkungen>
  <Catalogue_CH REF="ch.admin.are.nutzungsplanung_catalogue_ch.11"></Catalogue_CH>
</Nutzungsplanung_V1_2.Geobasisdaten.Typ_Kt>
```

Mit diesem `Typ_Kt` ist wiederum das Element `ch.admin.are.nutzungsplanung_catalogue_ch.11` aus dem Bundeskatalog verknüpft:

```xml
<Nutzungsplanung_V1_2.Catalogue_CH.Catalogue_CH TID="ch.admin.are.nutzungsplanung_catalogue_ch.11">
  <Code>11</Code>
  <Designation>
    <LocalisationCH_V1.MultilingualText>
      <LocalisedText>
        <LocalisationCH_V1.LocalisedText>
          <Language>de</Language>
          <Text>Wohnzonen</Text>
        </LocalisationCH_V1.LocalisedText>
        <LocalisationCH_V1.LocalisedText>
          <Language>fr</Language>
          <Text>Zones d'habitation</Text>
        </LocalisationCH_V1.LocalisedText>
        <LocalisationCH_V1.LocalisedText>
          <Language>it</Language>
          <Text>Zone residenziali</Text>
        </LocalisationCH_V1.LocalisedText>
      </LocalisedText>
    </LocalisationCH_V1.MultilingualText>
  </Designation>
</Nutzungsplanung_V1_2.Catalogue_CH.Catalogue_CH>
```

Soweit so logisch.

Für die Filterfunktion der Nutzungsplanung, also wie die Attribute aus dem MGDM ins ÖREB rüber kommen ist folgendes festgelegt:

![image](https://user-images.githubusercontent.com/3714179/232718990-ee9242fb-9214-476d-894e-508939b5330d.png)

Daraus schliesse ich, dass 1:1 die Stufe Gemeinde in den ÖREB-Kataster übertragen wird und somit für diesen Schritt der [Katalog des Bundes](http://models.geo.admin.ch/ARE/Nutzungsplanung_Catalogue_CH_V1_2_20210901.xml) keine Rolle spielt.

@edigonzales  & @romefi => Wie seht ihr das?

**Comment by romefi** [comment]
Richtig, für das ÖREB ist die Stufe Gemeinde entscheidend. Der Katalog des Bundes spielt bei der Nutzungsplanung keine Rolle.

**Comment by vvmruder** [comment]
Danke für die Ergänzung. Ich schliesse dieses Issue. Werde aber dann ggf. noch ein Neues aufmachen zu den Waldreservaten, falls es da auch noch Fragen gibt.
